### Register

POST http://localhost:8000/api/admin/register HTTP/1.1
Content-Type: application/json

{
    "first_name": "Julio",
    "last_name": "Felipe",
    "email": "julio@informach.com.br",
    "password": "123456",
    "password_confirm": "123456"
}

### Login

POST http://localhost:8000/api/admin/login HTTP/1.1
Content-Type: application/json

{
    "email": "new@new.com.br",
    "password": "new"
}

### Info
PUT http://localhost:8000/api/admin/users/info HTTP/1.1
Content-Type: application/json

{
    "first_name": "Helena",
    "last_name": "Oliveira",
    "email": "new@new.com.br"
}

### Password
PUT http://localhost:8000/api/admin/users/password HTTP/1.1
Content-Type: application/json

{
    "password": "new",
    "password_confirm": "new"
}

### Ambassadors
GET http://localhost:8000/api/admin/ambassadors HTTP/1.1