### Register

POST http://localhost:8000/api/admin/register HTTP/1.1
Content-Type: application/json

{
    "first_name": "Julio",
    "last_name": "Felipe",
    "email": "julio@informach.com.br",
    "password": "123456",
    "password_confirm": "123456"
}

### Login

POST http://localhost:8000/api/admin/login HTTP/1.1
Content-Type: application/json

{
    "email": "julio@informach.com.br",
    "password": "123456"
}

### User

GET  http://localhost:8000/api/admin/user HTTP/1.1
